apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-exchange
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-exchange
  template:
    metadata:
      labels:
        app: data-exchange
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh", "-c"]
        args: ["while true; do echo $(date) >> /data/output.txt; sleep 5; done"]
        volumeMounts:
        - name: shared-vol
          mountPath: /data
      - name: multitool
        image: wbitt/network-multitool
        command: ["/bin/sh", "-c"]
        args: ["tail -f /data/output.txt"]
        volumeMounts:
        - name: shared-vol
          mountPath: /data
      volumes:
      - name: shared-vol
        emptyDir: {}
